version: '3.7'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
volumes:    
      db:
networks:
  default:
      name: fanatik_network
    
